# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc",".rbenv-version","Rakefile","Gemfile","Gemfile.lock","changelog.md","README.md"] # files to exclude
auto: true
pygments: true
production: false
env : developement

# Configuration
title: Mesure Émoi
tagline: Présentation sur la conception de site
author:
  name: Mesure Émoi
  email: bertrand.keller@gmail.com
  github: bertrandkeller
  twitter: bertrandkeller
  feedburner: bertrandkeller
production_url: http://bertrandkeller.github.io/mesure-emoi/

# Jekyll bootstrap configuration
JB:
  version: 0.2.13
  BASE_PATH: http://bertrandkeller.github.io/mesure-emoi/
  ASSET_PATH: false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml
  comments:
    provider: false
    disqus:
      short_name: 
    livefyre:
      site_id: 123
    intensedebate:
      account: 123abc
    facebook:
      appid: 123
      num_posts: 5
      width: 580
      colorscheme: light
  analytics:
    provider: false
    google:
      tracking_id:
    getclicky:
      site_id: 
    mixpanel:
      token: _MIXPANEL_TOKEN_
  pingdom : 51764493e6e53dd01f000000
  sharing:
    provider: false
